# Generated by Django 3.2 on 2023-05-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_comment_review'),
        ('reviews', '0005_alter_title_category'),
    ]

    operations = [
    ]
