# Generated by Django 3.2 on 2023-05-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_category'),
        ('reviews', '0008_alter_review_title'),
    ]

    operations = [
    ]
