# Generated by Django 3.2 on 2023-05-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_merge_20230526_0650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сategory',
            new_name='Category',
        ),
    ]
