# Generated by Django 3.2 on 2023-05-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_review_constraint_author_title'),
        ('reviews', '0011_review_constraint_author_title'),
    ]

    operations = [
    ]
